# Generated by Django 6.1 on 2026-09-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otpcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_exp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_holder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
