# Generated by Django 6.1 on 2026-09-07 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50, verbose_name="To'lov turi / Karta")),
            ],
            options={
                'verbose_name': "Karta / To'lov usuli",
                'verbose_name_plural': "Karta / To'lov usullari",
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Klub nomi')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=100, verbose_name='Shahar')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kenglik (latitude)')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Uzunlik (longitude)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 2 (ixtiyoriy)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='clubs/photos/', verbose_name='Profil rasmi')),
                ('working_hours_from', models.TimeField(verbose_name='Ish vaqti (boshlanish)')),
                ('working_hours_to', models.TimeField(verbose_name='Ish vaqti (tugash)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Klublar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club-profiles/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Soatlik narx')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Bron qilinganmi?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='club.club', verbose_name='Klub')),
            ],
            options={
                'verbose_name': "O'rindiq",
                'verbose_name_plural': "O'rindiqlar",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('status', models.CharField(choices=[('booked', 'Bron qilingan'), ('playing', "O'ynalmoqda"), ('finished', 'Tugagan')], default='booked', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='club.card', verbose_name="To'lov usuli (Karta)")),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='club.seat', verbose_name="O'rindiq")),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Type_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='type_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.type_room'),
        ),
        migrations.CreateModel(
            name='Type_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='type_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.type_seat'),
        ),
    ]
