# Generated by Django 6.1 on 2026-08-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_booking_end_time_alter_booking_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50, verbose_name="To'lov turi / Karta")),
            ],
            options={
                'verbose_name': "Karta / To'lov usuli",
                'verbose_name_plural': "Karta / To'lov usullari",
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='club.card', verbose_name="To'lov usuli (Karta)"),
        ),
    ]
